(function(){
  function isoWeek(date){const d=new Date(date);d.setUTCHours(0,0,0,0);d.setUTCDate(d.getUTCDate()+4-(d.getUTCDay()||7));const year=d.getUTCFullYear();return {year,number:Math.ceil((((d-new Date(Date.UTC(year,0,1)))/86400000)+1)/7)};}
  function upcomingWeeks(now=new Date()) {const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=t=>Number(parts.find(p=>p.type===t).value);const today=new Date(Date.UTC(get('year'),get('month')-1,get('day')));return [0,1,2].map(i=>isoWeek(new Date(+today+i*7*86400000)));}
  function weekNumber(value){const s=String(value??'').trim();const m=/^(?:W|WK|WEEK|SEMANA|SEM)?\s*0?(\d{1,2})(?:\.0)?$/i.exec(s);return m&&+m[1]>=1&&+m[1]<=53?+m[1]:null;}
  function weeklyCounts(rows,weeks,key){const result=new Map();for(const row of rows){const index=weeks.findIndex(w=>w.number===weekNumber(row.week));if(index<0)continue;const name=String(row[key]||'').trim()||'Não informado';if(!result.has(name))result.set(name,weeks.map(()=>new Set()));result.get(name)[index].add(String(row.e||row.q));}return [...result].sort((a,b)=>a[0].localeCompare(b[0],'pt-BR')).map(([name,sets])=>[name,sets.map(s=>s.size)]);}
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  window.WeeklyDashboard={isoWeek,upcomingWeeks,weekNumber,weeklyCounts};
  window.renderWeekly=function(rows){const weeks=upcomingWeeks();const regions=weeklyCounts(rows,weeks,'u');const techs=weeklyCounts(rows,weeks,'k');const headings=weeks.map(w=>'W'+w.number);const regionTable='<table><thead><tr><th>Semana</th>'+regions.map(([n])=>'<th>'+esc(n)+'</th>').join('')+'</tr></thead><tbody>'+weeks.map((w,i)=>'<tr><th scope="row" title="'+w.year+'">'+headings[i]+'</th>'+regions.map(([,v])=>'<td>'+v[i]+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
  const techTable='<table><thead><tr><th>Técnico</th>'+headings.map((h,i)=>'<th title="'+weeks[i].year+'">'+h+'</th>').join('')+'</tr></thead><tbody>'+techs.map(([name,values])=>'<tr><th scope="row">'+esc(name)+'</th>'+values.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
  document.getElementById('weeklyStates').innerHTML=regionTable+(!regions.length?'<p>Sem sites programados nestas semanas.</p>':'');document.getElementById('weeklyTechs').innerHTML=techTable+(!techs.length?'<p>Sem sites programados nestas semanas.</p>':'');};
})();
